crud place
go-park-mail-ru/2024_2_ThereWillBeName pull request #20
Opened 2024-10-05 12:42 UTC by timurIsaevIY

2024-10-06 13:01 UTC, vr009 requested changes

2024-10-07 13:15 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +	_, err := r.db.ExecContext(ctx, "INSERT INTO places (name, image, description) VALUES ($1, $2, $3)", place.Name, place.Image, place.Description)
возвращает ссылку на объект с какими-то данными о вставке

2024-10-09 18:45 UTC, vr009 requested changes

2024-10-09 18:45 UTC, vr009 commented on cmd/main.go
> +	places.HandleFunc("search", handler.GetPlacesBySearchHandler).Methods(http.MethodGet)
Про урлы на созвоне говорил - надо поправить

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/delivery/http.go
> +		logger.Printf("Не удалось получить список достопримечательностей: %v", err)
В половине мест логи на русском, в другой половине на англ - надо к чему-то одному привести (англ)

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/delivery/http.go
> +		httpresponse.SendJSONResponse(w, nil, http.StatusInternalServerError)
Есть разные типы ошибок, нельзя на любую ошибку отдавать 500 - их надо различать

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	_, err := r.db.ExecContext(ctx, "INSERT INTO places (name, image, description) VALUES ($1, $2, $3)", place.Name, place.Image, place.Description)
Да, а почему эти данные игнорируются?

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	rows, err := r.db.QueryContext(ctx, "SELECT id, name, image, description FROM places where name LIKE $1", "%"+name+"%")
так нельзя делать - я вам так прям с сайта базу снести смогу скорее всего)

[почему смогу](https://en.wikipedia.org/wiki/SQL_injection)
[что с этим делать](https://go.dev/doc/database/sql-injection)

2024-10-09 18:45 UTC, vr009 commented on migrations/01_up.sql
> +    image VARCHAR(255) NOT NULL, -- путь к картинке
возможно лучше назвать как-то более явно этот аттрибут

2024-10-09 18:45 UTC, vr009 commented on migrations/01_up.sql
> +    city VARCHAR(255) NOT NULL, -- город, где находится место
Какие могут быть проблемы если город сделать текстовым полем как тут?

2024-10-09 18:45 UTC, vr009 commented on migrations/01_up.sql
> +    category VARCHAR(255) NOT NULL -- категория места
А что делать если понадобится больше категорий давать месту?

2024-10-09 18:45 UTC, vr009 commented on migrations/01_up.sql
> +    phoneNumber VARCHAR(255), -- номер телефона
очень много символов для номера телефона

2024-10-09 18:45 UTC, vr009 commented on migrations/01_up.sql
> +    numberOfReviews INT NOT NULL, -- количество отзывов
Какие есть альтернативы иметь эти данные как аттрибут places?

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/interfaces.go
> +	GetPlacesBySearch(ctx context.Context, name string) ([]models.Place, error)
Можно просто SearchPlaces

2024-10-09 18:45 UTC, vr009 commented on internal/pkg/places/interfaces.go
> +	GetPlacesBySearch(ctx context.Context, name string) ([]models.Place, error)
А этих методов вообще достаточно? Фронтенду хватит этих эндпоинтов?

2024-10-10 11:21 UTC, timurIsaevIY commented on migrations/01_up.sql
> +    category VARCHAR(255) NOT NULL -- категория места
сделать отдельную таблицу для категорий

2024-10-10 11:34 UTC, timurIsaevIY commented on internal/pkg/places/interfaces.go
> +	GetPlacesBySearch(ctx context.Context, name string) ([]models.Place, error)
В целом для продуктовых требований более чем достаточно, как я думаю, но раз ты спрашиваешь, то я что-то упустил. Единственное, что я вижу добавить - поиск по категориям, но как будто он пока излишен

2024-10-10 11:35 UTC, timurIsaevIY commented on migrations/01_up.sql
> +    numberOfReviews INT NOT NULL, -- количество отзывов
в отдельную таблицу вынести?

2024-10-10 11:37 UTC, timurIsaevIY commented on migrations/01_up.sql
> +    city VARCHAR(255) NOT NULL, -- город, где находится место
по разному город могут записать?

2024-10-13 07:49 UTC, vr009 commented on internal/pkg/places/delivery/http.go
> +		httpresponse.SendJSONResponse(w, nil, http.StatusInternalServerError)
Тут все еще на любую оишбку возвращается 500, то есть если пользователь попробует получить не существующий город ты мы вернем статус код который означает что ошибка произошла где-то на нашей стороне

2024-10-13 07:51 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +}
А если в базе будет 10тыс записей, что произойдет?

2024-10-13 07:52 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	}
А при какой ситуации в этом случае rowsAffected может быть 0?

2024-10-13 07:53 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	}
Остается проблема, что мы все еще не понимаем в хэндлерах какой статус код отдавать

2024-10-13 07:54 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	}
А ты тестировал этот запрос?

2024-10-14 09:43 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +}
памяти будет много занимать и времени, добавил limit и offset

2024-10-14 10:13 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +	}
ни в каком

2024-10-15 20:37 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +	stmt, err := r.db.PrepareContext(ctx, "SELECT id, name, imagePath, description FROM places where name LIKE $1")
А если тут 1000 записей на поиск выдастся?

2024-10-16 06:42 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +		return nil, fmt.Errorf("couldn't get places: %w", err)
да

2024-10-16 06:57 UTC, vr009 commented on internal/pkg/places/repo/place_repository.go
> +		return nil, fmt.Errorf("couldn't get places: %w", err)
а почему проценты тут а не в запросе основном прописаны?

2024-10-16 07:39 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +	}
исправил

2024-10-16 07:39 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +	stmt, err := r.db.PrepareContext(ctx, "SELECT id, name, imagePath, description FROM places where name LIKE $1")
исправил

2024-10-16 07:56 UTC, timurIsaevIY commented on internal/pkg/places/repo/place_repository.go
> +		return nil, fmt.Errorf("couldn't get places: %w", err)
исправил

2024-10-22 19:14 UTC, vr009 commented on internal/models/place.go
> +type CreatePlace struct {
Можно чуть более явно называть, типа `CreatePlaceRequest`

2024-10-22 19:15 UTC, vr009 commented on internal/pkg/categories/interfaces.go
> +type CategoryREpo interface {
REpo O_o :)

2024-10-23 17:16 UTC, merged